# Generated by Django 5.2.4 on 2025-09-22 18:55

from django.db import migrations
def data_color(apps, schema_editor):
    Color = apps.get_model('color', 'Color')

    for title in ['Negro','Azul','Verde','Blanco']:
        Color.objects.get_or_create(title=title)

class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_alter_color_creation_date'),
    ]

    operations = [
        migrations.RunPython(data_color),
    ]
