# Generated by Django 5.2.4 on 2025-07-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        ('suppliers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id_product', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('stock', models.IntegerField()),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('categories', models.ManyToManyField(related_name='products', to='category.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='suppliers.suppliers')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
