# Generated by Django 5.2.4 on 2025-07-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id_product', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('stock', models.IntegerField()),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('categories', models.ManyToManyField(related_name='products', to='category.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
