# Generated by Django 5.2.4 on 2025-09-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_table'),
        ('product', '0003_alter_product_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(related_name='products', to='order.order'),
        ),
    ]
