# Generated by Django 5.2.4 on 2026-01-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_creation_date'),
        ('color', '0003_data_color'),
        ('order', '0003_alter_order_options_remove_order_title_and_more'),
        ('product', '0005_product_color_product_size'),
        ('size', '0003_size_data'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el producto está disponible para la venta', verbose_name='Producto activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías a las que pertenece el producto', related_name='products', to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=1, help_text='Color del producto', on_delete=django.db.models.deletion.PROTECT, to='color.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(blank=True, help_text='URL de la imagen del producto', max_length=200, null=True, verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre del producto (máximo 100 caracteres)', max_length=100, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(blank=True, help_text='Órdenes que incluyen este producto', related_name='products', to='order.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=1, help_text='Tamaño del producto', on_delete=django.db.models.deletion.PROTECT, to='size.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(help_text='Cantidad en stock (debe ser 0 o mayor)', verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, help_text='Proveedores del producto', related_name='products', to='suppliers.suppliers'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='product_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['color'], name='product_color_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['size'], name='product_size_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['creation_date'], name='product_created_idx'),
        ),
    ]
