# Generated by Django 5.2.4 on 2026-02-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='products/', verbose_name='Imagen del producto'),
        ),
    ]
