# Generated by Django 5.2.4 on 2025-09-21 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='id_size', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=50)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
    ]
