# Generated by Django 5.2.4 on 2025-09-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
