# Generated by Django 5.2.4 on 2025-09-22 17:57

from django.db import migrations
def size_data(apps, schema_editor):
    Size = apps.get_model('size','Size')

    for title in ['S', 'M', 'L', 'XL', 'XXL']:
        Size.objects.get_or_create(title=title)


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0002_alter_size_creation_date'),
    ]

    operations = [
        migrations.RunPython(size_data),
    ]
