# Generated by Django 5.2.4 on 2025-09-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comany_name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Suppliers',
            },
        ),
    ]
