# Generated by Django 5.2.4 on 2025-09-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_populate_geo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='geo.city')),
            ],
            options={
                'db_table': 'Suppliers',
            },
        ),
    ]
