# Generated by Django 5.2.4 on 2025-09-21 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
