# Generated by Django 5.2.4 on 2025-09-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_suppliers_creation_date_suppliers_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='Country',
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
