# Generated by Django 5.2.4 on 2025-09-21 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('suppliers', '0003_remove_suppliers_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='comany_name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='geo.city'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='geo.country'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='geo.province'),
        ),
    ]
