# Generated by Django 5.2.4 on 2026-03-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_remove_order_title_and_more'),
        ('product', '0008_remove_product_order_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.AutoField(db_column='id_detail_order', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la compra', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='product.product')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
                'db_table': 'detail_order',
            },
        ),
    ]
