# Generated by Django 5.2.4 on 2025-09-21 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='id_country', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(db_column='id_province', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(db_column='province_country', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='geo.country')),
            ],
            options={
                'db_table': 'Province',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='id_city', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('province', models.ForeignKey(db_column='city_province', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.province')),
            ],
            options={
                'db_table': 'City',
            },
        ),
    ]
