# Generated by Django 5.2.4 on 2025-09-21 03:47

from django.db import migrations

def populate_geo_data(apps, schema_editor):
    Country = apps.get_model('geo', 'Country')
    Province = apps.get_model('geo', 'Province')
    City = apps.get_model('geo', 'City')

    # -------------------
    # Países
    # -------------------
    argentina = Country.objects.create(name='Argentina')
    brasil = Country.objects.create(name='Brasil')  # ejemplo extra

    # -------------------
    # Provincias de Argentina
    # -------------------
    provincias_arg = [
        'Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba', 'Corrientes', 
        'Entre Ríos', 'Formosa', 'Jujuy', 'La Pampa', 'La Rioja', 'Mendoza', 
        'Misiones', 'Neuquén', 'Río Negro', 'Salta', 'San Juan', 'San Luis', 
        'Santa Cruz', 'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego', 'Tucumán'
    ]

    provincia_objs = {}
    for nombre in provincias_arg:
        provincia_objs[nombre] = Province.objects.create(name=nombre, country=argentina)

    # -------------------
    # Ciudades de Misiones
    # -------------------
    ciudades_misiones = [
        'Posadas', 'Oberá', 'Eldorado', 'San Vicente', 'Apóstoles', 'Montecarlo',
        'Puerto Rico', 'Puerto Iguazú', 'San Javier', 'Campo Grande', 'Leandro N. Alem',
        'Candelaria', 'El Soberbio', 'San Ignacio', 'Garupá', 'Alba Posse', 'Capioví'
    ]

    for ciudad in ciudades_misiones:
        City.objects.create(name=ciudad, province=provincia_objs['Misiones'])

    # -------------------
    # Ejemplo mínimo de Brasil
    # -------------------
    sao_paulo = Province.objects.create(name='Sao Paulo', country=brasil)
    City.objects.create(name='Sao Paulo', province=sao_paulo)

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_geo_data),
    ]
